name: RiseOn Result Rial Package

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
  
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '9.0.x'

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release

        - name: Test
          run: dotnet test --no-restore --verbosity detailed

        - name: Publish
          run: dotnet publish --configuration Release --output ./publish --framework net9.0

        - name: Package
          run: dotnet pack --configuration Release --output ./publish

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: RiseOnResultRial
            path: ./publish

        #- name: Push to NuGet
          #env:
            #NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          #run: dotnet nuget push ./publish/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json