name: RiseOn Result Rial Package

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --configuration Release
        - name: Test
          run: dotnet test --no-restore --verbosity normal
        - name: Publish
          run: dotnet publish --configuration Release --output ./publish
        - name: Package
          run: dotnet pack --configuration Release --output ./publish
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2
          with:
            name: RiseOnResultRial